### ISSUE TITLE
is intersecting undefined

### ISSUE THREAD

**Issue by icodetree** [performance-lecture/lecture-3#14]
내용중에 질문이 있습니다.
아래 이미지 src값이 undefined값으로 나오는데 
target 하위를 확인해보니 entry.target.src 로 하면 나오는데
제가 잘못이해한건지 모르겠네요~~

console.log('is intersecting',entry.target.dataset.src);
>> is intersecting undefined

**Comment by hackurity01** [comment]
안녕하세요, icodetree님

정확히 어떤 내용 중에 질문을 하신 건지는 모르겠지만,
아마 intersectionObserver 설정을 할 때, 
jsx 코드에서 `src` attribute를 `data-src`로 변경해야 하는데,
그것을 빠뜨리신게 아닌가 생각됩니다.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/8624075/224467354-1282a739-0647-4f80-b2f4-2ae6fb62bba0.png">

**Comment by icodetree** [comment]
보내주신 내용으로 확인해보니 
제가 해당 코드를 빠뜨렸었네요~
빠른 피드백에 감사드립니다.^^
